apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: esports-ingress
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /pgadmin
            pathType: Prefix
            backend:
              service:
                name: pgadmin-service
                port:
                  number: 5050
          - path: /login
            pathType: Prefix
            backend:
              service:
                name: account-service
                port:
                  number: 9080
          - path: /users
            pathType: Prefix
            backend:
              service:
                name: account-service
                port:
                  number: 9080

#---
#
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: esports-ingress
#spec:
#  defaultBackend:
#    service:
#      name: postgres-service
#      port:
#        number: 5050
