apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: esports-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pgadmin-service
                port:
                  number: 5050

#---
#
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: esports-ingress
#spec:
#  defaultBackend:
#    service:
#      name: postgres-service
#      port:
#        number: 5050
